/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class edu_drexel_StatCollector_sensors_SystemCalls */

#ifndef _Included_edu_drexel_StatCollector_sensors_SystemCalls
#define _Included_edu_drexel_StatCollector_sensors_SystemCalls
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     edu_drexel_StatCollector_sensors_SystemCalls
 * Method:    add
 * Signature: (II)I
 */
JNIEXPORT jint JNICALL Java_edu_drexel_StatCollector_sensors_SystemCalls_add
  (JNIEnv *, jobject, jint, jint);

/*
 * Class:     edu_drexel_StatCollector_sensors_SystemCalls
 * Method:    hello
 * Signature: ()Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_edu_drexel_StatCollector_sensors_SystemCalls_hello
  (JNIEnv *, jobject);

/*
 * Class:     edu_drexel_StatCollector_sensors_SystemCalls
 * Method:    getSystemCalls
 * Signature: (I)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_edu_drexel_StatCollector_sensors_SystemCalls_getSystemCalls
  (JNIEnv *, jobject, jint);

#ifdef __cplusplus
}
#endif
#endif
